### ISSUE TITLE
excel 2007 can't open fastexcel  generate xlsx file

### ISSUE THREAD

**Issue by oyxiaogua** [dhatim/fastexcel#1]
dear sir/madam:
        i'm using fastexcel 0.8.1 to generate xlsx file,i found excel 2007 can't open the result file collect,
        the low version	 excel can't recognition the attribute  `<cols autoFit=\"true\">.`
	set the width of the column, the excel 2007 normal xml format is as follows:
        `<cols>
            <col min="1" max="1" width="21.375" customWidth="1"/>
            <col min="4" max="4" width="30.875" customWidth="1"/>
         </cols>	`

**Comment by ochedru** [comment]
Thank you for submitting this issue. The fix is in version 0.8.2.
