### ISSUE TITLE
Date format issue 

### ISSUE THREAD

**Issue by srinu936** [dhatim/fastexcel#106]
Hi , 
I am trying to  set custom date format using format method of style , it is changing actual date value to some other date with format required. how to fix this issue ?

public static void main(String[] args) {
		

		try( OutputStream os = new FileOutputStream("C:\\TESTOUTS\\testxls_"+(new Date().getTime())+".xlsx"))
		{
			Workbook   wb = new Workbook(os, "my workbook", "1.0"); 
		    Worksheet ws = wb.newWorksheet("test");
		    ws.style(2, 3).format("MMMM dd, yyyy").set();
		    ws.value(2, 3, new  SimpleDateFormat("dd/MMM/YYYY").parse("18/Apr/2020"));
		    wb.finish();
		     // Excepted output is : April 18, 2020
                    // Output return is : December 29 2020

			
			
		} catch (FileNotFoundException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		
		catch (Exception e) {
			e.printStackTrace();
		}

**Comment by rzymek** [comment]
The test below passes

    @Test
    public void dateIssue106() throws Exception {
        Date date = new SimpleDateFormat("dd/MMM/YYYY", Locale.ENGLISH).parse("18/Apr/2020");
        byte[] data = writeWorkbook(wb -> {
            Worksheet ws = wb.newWorksheet("Worksheet 1");
            ws.style(0, 0).format("MMMM dd, yyyy").set();
            ws.value(0, 0, date);
        });

        XSSFWorkbook xwb = new XSSFWorkbook(new ByteArrayInputStream(data));
        XSSFSheet xws = xwb.getSheetAt(0);
        Date value = xws.getRow(0).getCell(0).getDateCellValue();
        assertEquals(date, value);
    }


This got me thinking. Check this out:

    Date date = new SimpleDateFormat("dd/MMM/YYYY", Locale.ENGLISH)
      .parse("18/Apr/2020");
    System.out.println(date);
outputs:

    Sun Dec 29 00:00:00 CET 2019

So the problem is with date format patten (`dd/MMM/YYYY`), not date handing in fastexcel or poi.

The problem is with `YYYY`. [SimpleDateFormat](https://docs.oracle.com/javase/7/docs/api/java/text/SimpleDateFormat.html) docs state that `Y` is "Week year". You want `y` - year.

Change your pattern to `dd/MMM/yyyy` and you'll get what you want.

**Comment by srinu936** [comment]
Thanks for investigation , 
I forgot close this ticket , you absolutely right , I also found it with date pattern issue. 
Thank you,
