### ISSUE TITLE
Calling ws.value(x, y, value) when value is a Character

### ISSUE THREAD

**Issue by dorssar** [dhatim/fastexcel#129]
ws.value(0, 0, "a" as Character)

The following throws an exception:

java.lang.IllegalArgumentException: No supported cell type for class java.lang.Character
        at org.dhatim.fastexcel.Cell.setValue(Cell.java:106)
        at org.dhatim.fastexcel.Worksheet.value(Worksheet.java:495)

**Comment by rzymek** [comment]
If you have `char c = 'a'` then just call `ws.value(0,0,String.valueOf(c))`.

**Comment by rzymek** [comment]
In 0.11.0 release it is no longer possible to trigger this exception.  `value(row,col,v)` is no longer accepting Object - only the supported types.
