### ISSUE TITLE
Using stream when calling sheet.value

### ISSUE THREAD

**Issue by ghahramani** [dhatim/fastexcel#133]
Hi,

I was wondering, would it be possible to put the data as a stream whenever a user call `sheet.value()` or maybe introducing a function like flush can be called manually whenever the need to put the memory into a stream?

**Comment by rzymek** [comment]
Could you elaborate? Maybe post some sample code you would want to write. Are you talking about reading or writing?

There is a `sheet.flush()` method in fastexcel-writer that writes all the rows from memory to the output stream and frees memory.

**Comment by ghahramani** [comment]
Ah, yeah, sorry for the confusion, I didn't see the method in the documentation I thought it might not be there, shortly after I created the issue found it. I will close the ticket.

Thank you
