### ISSUE TITLE
Migrate from Travis CI to Github actions

### ISSUE THREAD

**Issue by ochedru** [dhatim/fastexcel#141]
Travis CI is shutting down.

**Comment by rzymek** [comment]
I think only travis-ci.org is shutting down and migrating to travis-ci.com is an option. Still free for open source I think.

Nevertheless I can take a bite at GitHub Actions. I wanted to get to know them anyway

**Comment by ochedru** [comment]
I have just migrated https://github.com/dhatim/root-pom-oss. I'll open a PR on fastexcel.
