### ISSUE TITLE
NullPointer on import of the empty excel file

### ISSUE THREAD

**Issue by PetarPilipovic** [dhatim/fastexcel#151]
Hi, 

when trying to import completely new excel file (just created and without any data within) I am getting NPE on 

`org.dhatim.fastexcel.reader.OPCPackage.getEntryContent(String)` on the line 97

On debug, I could see that sharedStrings on parts is null

![image](https://user-images.githubusercontent.com/78962455/107767587-721b0600-6d35-11eb-914e-dee160e1e243.png)

I am using the latest (0.12.3) version.

**Comment by ochedru** [comment]
Should be fixed by https://github.com/dhatim/fastexcel/pull/147: please try version 0.12.5.
