### ISSUE TITLE
OutOfMemory when reading large excel file

### ISSUE THREAD

**Issue by spiderman510** [dhatim/fastexcel#152]
Follow your example, but i got OutOfMemory error if reading large excel file (1GB). Small one(200MB) still good.
Here is the line throw error because of reading whole excel file and store to memory
ReadableWorkbook wb = new ReadableWorkbook(is)

**Comment by rzymek** [comment]
Use the other constructor. The one that takes a File

**Comment by danmaidesenling** [comment]
> Follow your example, but i got OutOfMemory error if reading large excel file (1GB). Small one(200MB) still good.
> Here is the line throw error because of reading whole excel file and store to memory
> ReadableWorkbook wb = new ReadableWorkbook(is)

@spiderman510  Have you fixed the OOM issue ?
