### ISSUE TITLE
Question: Edit an existing excel file

### ISSUE THREAD

**Issue by anragab** [dhatim/fastexcel#167]
I have a template excel file that I want to use as a starting point. 

Is it possible to add/edit data in a pre-existing worksheet in that excel file?

**Comment by Arnotjevleesch** [comment]
Do you think it's something possible or the lib is not made for that ?

**Comment by svpace** [comment]
I don't think that OP is talking about xltx support. Just using an existing xslx (perhaps with some formatting or formulas) and adding new content to it.
