### ISSUE TITLE
Evaluating Formulas

### ISSUE THREAD

**Issue by akashraj11** [dhatim/fastexcel#171]
Can the fastexcel reader be used to read sheets with formulas evaluated ? 

I tried implementing excel file reader using Apache POI streaming reader, but using streaming reader I was not able to evaluate formulas and read. 
I had to implement non streaming reader using Apache POI to read sheets which has formulas, but this was throwing Java heap space error when reading excel files with more than 10 million rows. 

 Does the fastexcel library support reading excel files with 10 million or greater rows with formulas by evaluating Formulas while reading?

**Comment by ochedru** [comment]
Fastexcel reader does not evaluate formulas.
