### ISSUE TITLE
 `Worksheet.isCellInMergedRanges` make write slow.

### ISSUE THREAD

**Issue by jilen** [dhatim/fastexcel#185]
For example
`10000 rows x 20 cols x 100 merged regions`
There could be `10_000_000`  `Worksheet.isCellInMergedRanges` iterations.

**Comment by jilen** [comment]
Possible solution:
- Just treat  cells in merged region as normal cell while calc width
- Use some data structure like `r-tree` instead of set.

**Comment by ochedru** [comment]
Thanks for your feedback.
Indeed, we could use a better data structure for `mergedRanges` or rethink column width computation, which is not perfect anyway.
