### ISSUE TITLE
ReadableWorkbook constructor with File and ReadingOptions

### ISSUE THREAD

**Issue by AstrorEnales** [dhatim/fastexcel#191]
First, thanks for this project! It solved the memory and speed issues i had with apache poi.

As the InputStream constructor copies all bytes to memory, i would be happy to use the File constructor of ReadableWorkbook, however, i also need the ReadingOptions to read cell data formats. So it would be wonderful, if you could add a constructor overload with these two parameters:
`public ReadableWorkbook(File inputFile, ReadingOptions readingOptions) throws IOException {
  this(OPCPackage.open(inputFile, readingOptions.isWithCellFormat()), readingOptions);
}`

As it's only three lines of code, i refrained from creating a whole fork and pull request.

**Comment by ochedru** [comment]
Thank you for your feedback. I'll do the PR.
