### ISSUE TITLE
Bug parsing Dates?

### ISSUE THREAD

**Issue by ThanosFisherman** [dhatim/fastexcel#20]
I'm having trouble reading dates from excel file. FastExcel doesn't recognize DATE type fields so it parses them as NUMBER instead and gives me something like 40333.
I don't have this problem with Apache POI.

**Comment by Albatarm** [comment]
Hi, could you give me an excel file that cause this behavior ? I already test date reading in unit tests but is seems that date are not always encoded in the same way.

**Comment by ThanosFisherman** [comment]
Hello,
Sure have a look at the attached file. Also find my code below which essentially converts the excel file into csv format.
```java
//where read happens
  for (int i = 0; i < rows.size(); i++) {
        for (int j = 0; j < colCount; j++) {
          String cellValue;
          if (rows.get(i).hasCell(j)) cellValue = getCellData(rows.get(i).getCell(j));
          else cellValue = "NULL"
          stringBuilder.append(cellValue).append(j < colCount - 1 ? CSV_SEPERATOR_CHAR : "");
        }
        stringBuilder.append(i < rows.size() - 1 ? NEW_LINE_CHARACTER : "");
      }

//get the appropriate value.
 private String getCellData(@Nullable Cell myCell) {
    if (myCell == null) return "NULL";
    final String cellDataStr;
    switch (myCell.getType()) {
      case STRING:
        cellDataStr = myCell.asString();
        break;
      case BOOLEAN:
        cellDataStr = Boolean.toString(myCell.asBoolean());
        break;
      case NUMBER:
        cellDataStr = myCell.asNumber().toString();
        break;
      case FORMULA:
        cellDataStr = myCell.getFormula();
        break;
      case DATE:
        cellDataStr = myCell.asDate().format(DateTimeFormatter.ofPattern(OUTPUT_DATE_FORMAT));
        break;
      case ERROR:
        cellDataStr = "ERROR";
        break;
      case EMPTY:
        cellDataStr = "EMPTY";
        break;
      default:
        cellDataStr = myCell.getText();
    }
    return cellDataStr;
  }
```
[MidcoastAnimalHospital_NSW_2428.xlsx](https://github.com/dhatim/fastexcel/files/1966703/MidcoastAnimalHospital_NSW_2428.xlsx)

**Comment by Albatarm** [comment]
In fact, there is no date type in OpenXML office format version 2007. Dates are encoded as number and cells with date are using a built-in style format to format number as date.

So the best think to do is to remove date type in `org.dhatim.fastexcel.reader.CellType` and to let tools methods to decode dates from number cell.

**Comment by Albatarm** [comment]
My suggestion is in this pull request https://github.com/dhatim/fastexcel/pull/21.
It is not possible to determine date cell type without reading cell styles. As I explained dates are just number cells with a date display format.
This library don't read styles, it concentrates on cells content.

In your source code, you can't use this to determine dates. 
```java
case DATE:
        cellDataStr = myCell.asDate().format(DateTimeFormatter.ofPattern(OUTPUT_DATE_FORMAT));
        break;
```

You can use the method `org.dhatim.fastexcel.reader.Cell#getRawValue` do get raw value of a cell. But date values are number so I think it will not help you.

A possible solution is to write a cell style reader and to detect date time patterns in number formats.

**Comment by ThanosFisherman** [comment]
I see. Thanks for the info. You are right `org.dhatim.fastexcel.reader.Cell#getRawValue` doesn't help. It just returns the same numbers. 

So for now there is no way to determine day/month/year from those returned numbers.

**Comment by Albatarm** [comment]
You can transform these numbers into dates with `org.dhatim.fastexcel.reader.Cell#asDate`.
But this method will always return a date with a number cell, even if the number do not represent a date.

**Comment by realtica** [comment]
> I see. Thanks for the info. You are right `org.dhatim.fastexcel.reader.Cell#getRawValue` doesn't help. It just returns the same numbers.
> 
> So for now there is no way to determine day/month/year from those returned numbers.

Same, here.

And if the cell is a formula we get this..
org.dhatim.fastexcel.reader.ExcelReaderException: Wrong cell type FORMULA for date value
