### ISSUE TITLE
Export to Excel needs decimal digit format control

### ISSUE THREAD

**Issue by Jack-eliteSoho** [dhatim/fastexcel#218]
Export to Excel, all the numbers are in Number formatter with 2-digit decimal.

how to format the decimal, like no decimal, 2 decimals, or 4 decimals? and how to set default decimal like no decimal, then override the default decimal for certain cells with 2 decimal, or 4 decimal?

also, possible to have Accounting formatter for all the numbers?

**Comment by ochedru** [comment]
You can use `Worksheet.style(row, column).format("...")` to change number formatting for a given cell.
For example to display 1234.6 when the number is 1234.59, use format "####.#". More examples are available here: https://support.microsoft.com/en-us/office/number-format-codes-5026bbd6-04bc-48cd-bf33-80f18b4eae68.
