### ISSUE TITLE
How to read password protected Excel files

### ISSUE THREAD

**Issue by neoamuro** [dhatim/fastexcel#244]
If I read password protected Excel files, it is occur the exception "InvalidDataException".

Is there any options to read password protected Excel files by the FastExcel?

**Comment by meiMingle** [comment]
As far as I know, this project does not currently support reading encrypted documents. But you can get the decrypted data stream with the help of POI, and then use this library to read the data.
```java
        POIFSFileSystem fileSystem = new POIFSFileSystem(new File("D://protectedTest.xlsx"));
        EncryptionInfo info = new EncryptionInfo(fileSystem);
        Decryptor d = Decryptor.getInstance(info);
        try {
            if (!d.verifyPassword("1234")) {
                throw new RuntimeException("Unable to process: document is encrypted");
            }
            // parse dataStream
            try (InputStream dataStream = d.getDataStream(fileSystem); ReadableWorkbook fworkbook = new ReadableWorkbook(dataStream)) {
                Sheet sheet = fworkbook.getSheet(0).orElse(null);
                assert sheet != null;
                sheet.openStream().forEach(System.out::println);
            }
        } catch (GeneralSecurityException ex) {
            throw new RuntimeException("Unable to process encrypted document", ex);
        }

```
[protectedTest.xlsx](https://github.com/dhatim/fastexcel/files/10365657/protectedTest.xlsx)

**Comment by meiMingle** [comment]
You can also generate a protected excel file using a similar method, as follows. But there is a disadvantage in this method at present. The generated file can be opened normally by Microsoft Office, but it cannot be read correctly by fastexcel-reader.
```java
        POIFSFileSystem fileSystem = new POIFSFileSystem(new File("D://protectedTest.xlsx"));
        EncryptionInfo info = new EncryptionInfo(fileSystem);
        Decryptor d = Decryptor.getInstance(info);
        try {
            if (!d.verifyPassword("1234")) {
                throw new RuntimeException("Unable to process: document is encrypted");
            }
            // parse dataStream
            try (InputStream dataStream = d.getDataStream(fileSystem); ReadableWorkbook fworkbook = new ReadableWorkbook(dataStream)) {
                Sheet sheet = fworkbook.getSheet(0).orElse(null);
                assert sheet != null;
                sheet.openStream().forEach(System.out::println);
            }
        } catch (GeneralSecurityException ex) {
            throw new RuntimeException("Unable to process encrypted document", ex);
        }

```

**Comment by neoamuro** [comment]
> You can also generate a protected excel file using a similar method, as follows.
> 
> ```java
>     try (ByteArrayOutputStream bos = new ByteArrayOutputStream(); POIFSFileSystem fs = new POIFSFileSystem()) {
>         Workbook wb = new Workbook(bos, "Test", "1.0");
>         wb.setGlobalDefaultFont("Arial", 15.5);
>         Worksheet ws = wb.newWorksheet("Worksheet 1");
>         ws.value(0, 0, "Hello fastexcel");
>         wb.finish();
>         byte[] bytes = bos.toByteArray();
>         EncryptionInfo info = new EncryptionInfo(EncryptionMode.agile);
>         // EncryptionInfo info = new EncryptionInfo(EncryptionMode.agile, CipherAlgorithm.aes192, HashAlgorithm.sha384, -1, -1, null);
>         Encryptor enc = info.getEncryptor();
>         enc.confirmPassword("1234");
>         // Read in an existing OOXML file and write to encrypted output stream
>         // don't forget to close the output stream otherwise the padding bytes aren't added
>         try (OPCPackage opc = OPCPackage.open(new ByteArrayInputStream(bytes)); OutputStream os = enc.getDataStream(fs)) {
>             opc.save(os);
>         }
>         // Write out the encrypted version
>         try (FileOutputStream fos = new FileOutputStream("D://protectedTest.xlsx")) {
>             fs.writeFilesystem(fos);
>         }
>     }
> ```

Thank you for your help~!
Your solution helped me a lot~!!
