### ISSUE TITLE
Is there any function to group rows?

### ISSUE THREAD

**Issue by dgappc** [dhatim/fastexcel#259]
Excel has the functionality to be able to group rows, so that you can hide and show the rows by clicking bars in the leftmost column. 

Is this functionality supported while writing an excel file using fastexcel?

Thanks

**Comment by meiMingle** [comment]
If you just hide multiple rows of cells, you can do this

```java

IntStream.rangeClosed(2,9).forEach(ws::hideRow);

```

**Comment by meiMingle** [comment]
But I found that the functions that hide rows or columns might be a bit problematic, see #261 .  I'll try to fix it.

**Comment by dgappc** [comment]
I am afraid hiding rows is not what we are looking for, but rather grouping rows. See the attached excel with open/close buttons on the left. Currently we are doing this with POI, but it is rather slow.

Thanks
[Budget_HR_Base_Salary_Expense_20230131193917.xlsx](https://github.com/dhatim/fastexcel/files/10553086/Budget_HR_Base_Salary_Expense_20230131193917.xlsx)

**Comment by meiMingle** [comment]
OK I get it, there is no such feature at the moment, I will try to implement it

**Comment by dgappc** [comment]
Thanks very much.

**Comment by meiMingle** [comment]
@dgappc Now it's available in v0.14.18, you can try it

**Comment by dgappc** [comment]
Great! It works, thanks.
