### ISSUE TITLE
Excel update operation

### ISSUE THREAD

**Issue by dskumar101** [dhatim/fastexcel#284]
I see we can read and write using fastexcel-reader and fastexcel-writer respectively. However, I have a scenario where I need to update existing excel with data. Can you suggest how I can achieve this? Thanks

**Comment by ochedru** [comment]
Indeed, fastexcel-writer is not able to update an existing workbook.
For this scenario, you could use Apache POI.
If you have many updates, however, it may be beneficial to read the existing workbook with fastexcel-reader and create a new workbook using fastexcel-writer.
