### ISSUE TITLE
Issue when setting a cell value string with \b or \u0001 character

### ISSUE THREAD

**Issue by andma1** [dhatim/fastexcel#29]
![image](https://user-images.githubusercontent.com/41778180/43644831-21d20670-9741-11e8-8ccd-2d9f1eb4cd6b.png)

or 
![image](https://user-images.githubusercontent.com/41778180/43646333-b25cf1ce-9745-11e8-9e46-fcb2d1689302.png)

I had same problem with emojis,

I'm trying to set  cell value a string, which contains \b\n character, the file is generated without errors, but when I open it  I see this 

![image](https://user-images.githubusercontent.com/41778180/43315366-cf8caa5e-91a6-11e8-83f0-aed56180dfad.png)

![image](https://user-images.githubusercontent.com/41778180/43315376-d7fdff26-91a6-11e8-9f1d-02efd2e69f1b.png)

Can you fix this for all unicode characters?

**Comment by ochedru** [comment]
You are right, in XML 1.0, only characters with unicode code points #x9, #xA, #xD, [#x20-#xD7FF], [#xE000-#xFFFD] or [#x10000-#x10FFFF] are accepted are escaped if necessary. Other characters should be ignored.
