### ISSUE TITLE
Corrupted file when generating excel 

### ISSUE THREAD

**Issue by inkman97** [dhatim/fastexcel#306]
Hi,
We are using latest version of fastexcel in our project. It worked since Java 11 but now that we have migrated to Java 17 the excel file that is generated is corrupted.
The strange behaviour is that if I generate the excel in local environment running on Java 17 the excel is correctly generated, but if I execute it in dev environment it gives the problem mentioned before. Only difference between the two is that local environment is on Windows machine and dev is on Linux.

Do you know what can be the issue?

Thanks in advance!

**Comment by rzymek** [comment]
The first thing I'd check is if you're not missing any close() method call (or use try-with-resources like in the [sample](https://github.com/dhatim/fastexcel#simple-workbook))

**Comment by inkman97** [comment]
Sure I'll check this first and will give an answer after. If this should be the case then how it's working fine locally and not on another env?

**Comment by rzymek** [comment]
Windows and Linux have a totally different way of handling files. It might be working fine (by "accident") with a call to close() on Windows and fail on Linux. Or vice versa.

**Comment by rzymek** [comment]
No really. I think the operating system makes the real difference here

**Comment by inkman97** [comment]
> No really. I think the operating system makes the real difference here

I checked on the code and we are creating workbook and related worksheet as stated on the readme file. Do you have other suggestions? Thanks!

**Comment by inkman97** [comment]
> No really. I think the operating system makes the real difference here

I checked the code and we are using CompletableFuture. I've checked another issue that is still opened in fastexcel project and it seems it's the same problem. What do you suggest?

**Comment by rzymek** [comment]
How are you using `CompletableFuture`? Fastexcel, as generally all io streams, is not thread-safe.

**Comment by inkman97** [comment]
> How are you using `CompletableFuture`? Fastexcel, as generally all io streams, is not thread-safe.

Yes for this reason I removed it and I structured the code in order to remove multi thread, but the error still persists. The situation I'm facing is the same mentioned into another open issue on fastexcel repo. We just create a workbook and from that workbook we set the values for each worksheet in that workbook. After this we call the finish() on workbook object and we close output stream. Do you have some suggestions?

**Comment by TuzSeRik** [comment]
I stumbled upon this problem. My code is pretty simple:

```
try (OutputStream stream = new FileOutputStream(file)) {
            Workbook workbook = new Workbook(stream, name, version.substring(0, version.lastIndexOf(".")));
            for(Sheet sheet : book.getSheets()) {
                for (Map.Entry<Integer, Row> row : sheet.getRows().entrySet()) {
                    for (Map.Entry<Integer, Cell> cell : row.getValue().getCells().entrySet()) {
                        switch (cell.getValue().getType()) {
                            // Indexes start from 1 so we need to -1 them
                            case STRING -> worksheet.value(row.getKey() - 1, cell.getKey() - 1, cell.getValue().getValue());
                            case NUMBER -> worksheet.value(row.getKey() - 1, cell.getKey() - 1, Double.valueOf(cell.getValue().getValue()));
                            case BOOLEAN -> worksheet.value(row.getKey() - 1, cell.getKey() - 1, Boolean.getBoolean(cell.getValue().getValue()));
                            case DATE -> worksheet.value(row.getKey() - 1, cell.getKey() - 1, Date.from(Instant.parse(cell.getValue().getValue())));
                            case LOCAL_DATE -> worksheet.value(row.getKey() - 1, cell.getKey() - 1, LocalDate.parse(cell.getValue().getValue()));
                            case LOCAL_DATE_TIME -> worksheet.value(row.getKey() - 1, cell.getKey() - 1, LocalDateTime.parse(cell.getValue().getValue()));
                            case ZONED_DATE_TIME -> worksheet.value(row.getKey() - 1, cell.getKey() - 1, ZonedDateTime.parse(cell.getValue().getValue()));
                        }
                    }
                }

                worksheet.flush();
                worksheet.finish();
                worksheet.close();
            }

            workbook.finish();
            workbook.close();
        } catch (IOException e) {
            throw new RuntimeException(e);
        }
```

Yet Excel treats file as corrupted. After it recovers it (saying that data was repaired or deleted) with no visible changes, resaved file size then 50% bigger than non-repaired one (9kb vs 6kb). Is there any possible explanation for this?

**Comment by kjit** [comment]
Hi, I had similar issue, generated file was recognized as corrupted by Excel. In my case the problem was, that I've called workbook.finish() twice: one time explicit, second by autocloseable feature. 
So such piece of code generates invalid file:
```  
 public static void main(String[] args) throws IOException {
        String name = "testexcel.xlsx";
        try (OutputStream os = new FileOutputStream(name); Workbook wb = new Workbook(os, "MyApplication", "1.0")) {
            Worksheet ws = wb.newWorksheet("Sheet 1");
            ws.value(0, 0, "This is a string in A1");
            ws.value(0, 1, new Date());
            ws.value(0, 2, 1234);
            ws.value(0, 3, 123456L);
            ws.value(0, 4, 1.234);
            wb.finish();
        }
    }
```
Once I removed wb.finish(), file is generated correctly. So I recommend to double check if this method is not called twice somehow.
Env: Windows, Java 17

**Comment by inkman97** [comment]
@kjit In my case the issue was related to timestamp because it was not compatible with java time using java 17. So I changed the timestamp and it worked
