### ISSUE TITLE
Support for adding hyperlinks

### ISSUE THREAD

**Issue by Asraiel** [dhatim/fastexcel#31]
Some other libraries support adding Hyperlinks. As I am migrating an older project from Apache Poi to fastexcel, I would be gracious for the addition of such a functionality.

![image](https://user-images.githubusercontent.com/4643888/44096490-a96e627a-9fdb-11e8-95ee-04f14e03c207.png)

**Comment by ochedru** [comment]
Did you try using the `HYPERLINK` formula operator? See https://stackoverflow.com/questions/2905633/add-hyperlink-to-cell-in-excel-2007-using-open-xml-sdk-2-0/13074304.

**Comment by Asraiel** [comment]
That works fine, thank you.
For reference, I used the following code:
`ws.formula(r, c, "HYPERLINK(\"www.google.com\")"); // only shows link`
`ws.formula(r, c, "HYPERLINK(\"www.google.com\"; \"Google\")"); // shows text with link`
