### ISSUE TITLE
(support) is there any method like setTabColor to set tabs in different color？？

### ISSUE THREAD

**Issue by GuopingYe** [dhatim/fastexcel#313]
As the title. Thanks for ur help!

**Comment by meiMingle** [comment]
I don't fully understand what you're asking for, if you could give an example or provide some samples to show what you want, maybe I can help solve it.

**Comment by GuopingYe** [comment]
> I don't fully understand what you're asking for, if you could give an example or provide some samples to show what you want, maybe I can help solve it.

thanks for ur help, please refer to POI, https://www.tabnine.com/code/java/methods/org.apache.poi.xssf.usermodel.XSSFSheet/setTabColor

**Comment by meiMingle** [comment]
```xml
        <repositories>
		<repository>
		    <id>jitpack.io</id>
		    <url>https://jitpack.io</url>
		</repository>
	</repositories>

        <dependency>
	    <groupId>com.github.meiMingle.fastexcel</groupId>
	    <artifactId>fastexcel</artifactId>
	    <version>feature-setTabColor-SNAPSHOT</version>
	</dependency>
```
@GuopingYe Before this repository manager merges my PR, you can temporarily use the above dependencies for testing
