### ISSUE TITLE
How to wrap text within cell.

### ISSUE THREAD

**Issue by shajahan86** [dhatim/fastexcel#44]
Hi.

When I am generating the Excel. Mentioned text shows in single line within a cell.  Below image for your reference.

![single_line](https://user-images.githubusercontent.com/6029754/49854618-bd14f800-fe10-11e8-9375-f7133ce20b95.jpg)

But I want text like below image within a cell.
![wrap text](https://user-images.githubusercontent.com/6029754/49854695-06654780-fe11-11e8-9a3a-a882549a5ed5.png)

Thanks.

**Comment by ochedru** [comment]
Use the `wrapText` property and `\n` in the cell text value to set line breaks:
```java
ws.style(0,0).wrapText(true).set();
ws.value(0, 0, "firt line\nsecond line");
```
Row height is adjusted accordingly by Excel (auto fit). However, note row height auto fit does not work with merged cells: this is a known problem in Excel: https://support.microsoft.com/en-us/help/212010/you-cannot-use-the-autofit-feature-for-rows-or-columns-that-contain-me.
