### ISSUE TITLE
Load image

### ISSUE THREAD

**Issue by shajahan86** [dhatim/fastexcel#45]
How to load image in cell?

**Comment by shajahan86** [comment]
Hi, 
I don't know how to put image in cell. Please help me as soon as possbile.

**Comment by ochedru** [comment]
This is not yet supported (this library was initially designed for simple workbooks).
Maybe you can use fastexcel to create your workbook without images and then use Apache POI to add images into the generated workbook: https://stackoverflow.com/questions/28238078/insert-image-in-column-to-excel-using-apache-poi.

**Comment by shajahan86** [comment]
Thanks for your reply
