### ISSUE TITLE
Is it possible to set width for specific column?

### ISSUE THREAD

**Issue by shajahan86** [dhatim/fastexcel#46]
Is it possible to set width for specific column?

**Comment by shajahan86** [comment]
Or auto size

**Comment by ochedru** [comment]
Sure: please check out https://static.javadoc.io/org.dhatim/fastexcel/0.9.8/org/dhatim/fastexcel/Worksheet.html#width-int-double-.
Autosizing is by default, but it is not perfect: see issue #35.
