### ISSUE TITLE
Will you provide jar file for 0.9.8?

### ISSUE THREAD

**Issue by shajahan86** [dhatim/fastexcel#47]
Will you provide jar file for 0.9.8?

**Comment by ochedru** [comment]
As described in the [readme](https://github.com/dhatim/fastexcel/blob/master/README.md), fastexcel is mavenized so its artifacts are present in maven central.
If you do not use maven or gradle, you can still download the artifacts from central yourself: https://search.maven.org/artifact/org.dhatim/fastexcel/0.9.8/jar.

**Comment by shajahan86** [comment]
Thanks
