### ISSUE TITLE
Bordercolor not working

### ISSUE THREAD

**Issue by shajahan86** [dhatim/fastexcel#48]
Hi,

Border color not working using this method. Please help me.
ws.style(i, j).bold().fontSize(9).borderColor(BorderSide.BOTTOM,"FF0000").set();

**Comment by ochedru** [comment]
You must set a border thickness first. By default there is no border, so changing its color only has no effect. Please check out the javadoc for a link to the Microsoft doc listing accepted border styles.
For example:
```java
ws.style(i, j).bold().fontSize(9).borderStyle(BorderSide.BOTTOM, "thin").borderColor(BorderSide.BOTTOM,"FF0000").set();
```
