### ISSUE TITLE
Hyperlink covers whole cell

### ISSUE THREAD

**Issue by bohledevs** [dhatim/fastexcel#484]
Hello everyone. I'm currently using Fastexcel and it's a performance miracle. Love it so far.

I'm having trouble with hyperlinks, though. I must set a reference over part of the cell's text, not all of it.

For example,

"Visit us --here--" - Hyperlink in --here--

Couldn't achieve it, as hyperlink covers all of the cell.

Any alternatives?

**Comment by meiMingle** [comment]
I understand your intention, but I have tried and I can't find a way to achieve this in Microsoft Excel. Maybe this is not supported (at least on Microsoft Excel), or maybe I lack the skills, or you can provide an xlsx file that achieves this goal so that I can solve this problem well.

**Comment by bohledevs** [comment]
@meiMingle My bad. Tried on Microsoft Excel as well and couldn't achieve it. The requirement came from a Google Sheets template. So, based on your response, I will challenge it in favor of a workaround, thanks for the reply.
