### ISSUE TITLE
Null pointer Exception in (org.dhatim.fastexcel.reader.Sheet) sheet).openStream()

### ISSUE THREAD

**Issue by SujathaThazhal** [dhatim/fastexcel#60]
When try to open stream getting null pointer exception in XSSFReader of  PackageRelationship rel = workbookPart.getRelationship(relId); line number 174

**Comment by SujathaThazhal** [comment]
java.lang.NullPointerException: null
	at org.dhatim.fastexcel.reader.Sheet.<init>(Sheet.java:33)
	at org.dhatim.fastexcel.reader.ReadableWorkbook.createSheet(ReadableWorkbook.java:122)
	at org.dhatim.fastexcel.reader.SimpleXmlReader.forEach(SimpleXmlReader.java:87)
	at org.dhatim.fastexcel.reader.ReadableWorkbook.readWorkbook(ReadableWorkbook.java:108)
	at org.dhatim.fastexcel.reader.ReadableWorkbook.<init>(ReadableWorkbook.java:74)
	at org.dhatim.fastexcel.reader.ReadableWorkbook.<init>(ReadableWorkbook.java:58)

**Comment by ochedru** [comment]
Can you post a code snippet to reproduce the problem? Thank you.

**Comment by rzymek** [comment]
It might be connected with https://github.com/dhatim/fastexcel/pull/62

@SujathaThazhal you probably have another `XmlInputFactory` provider on your classpath.

Try adding this line before reading the workbook:
```java
System.setProperty("javax.xml.stream.XMLInputFactory", 
   "com.sun.xml.internal.stream.XMLInputFactoryImpl");
```
It that helps, then the next release of fastexcel-reader will fix your issue.

**Comment by SujathaThazhal** [comment]
Dear Team ,

Sorry for the delay . The problem is readworkbook parse and create sheet
when then input generated from buffered input stream .

Other than BIS .. getting null pointer exception.. because the Sheet is
created with null id.

Will reply you further details ..of my analysis .

Thanks
Sujatha

**Comment by SujathaThazhal** [comment]
Hi Team,

I have no luck, when i use the above system property values. even if i try
to fetch the Sheet by Name not working well. Any other way to resolve
this issue?.

**Comment by rzymek** [comment]
As @ochedru mentioned - please post a code snippet to reproduce the problem? Show us how you are calling fastexcel. The xlsx file would also be helpful if you can share it.

**Comment by SujathaThazhal** [comment]
I am Using the same xlsx while available in the  resource folder. the
differences are

1. I am using the below dependencies in pom.xml
2. I am running the   SimpleReaderTest.java junit  file from  my project,
which cause the r.getAttribute = null when i try to convert the input
stream to readWorkbook.

<dependency>
<groupId>com.fasterxml.jackson.core</groupId>
<artifactId>jackson-databind</artifactId>
<version>${jackson.version}</version>
</dependency>

<dependency>
<groupId>com.fasterxml.jackson.core</groupId>
<artifactId>jackson-core</artifactId>
<version>${jackson.version}</version>
</dependency>

<dependency>
<groupId>com.fasterxml.jackson.core</groupId>
<artifactId>jackson-annotations</artifactId>
<version>${jackson.version}</version>
</dependency>

<dependency>
<groupId>com.fasterxml.jackson.dataformat</groupId>
<artifactId>jackson-dataformat-xml</artifactId>
<version>${jackson.version}</version>
</dependency>

<dependency>
<groupId>org.apache.poi</groupId>
<artifactId>poi</artifactId>
<version>3.17</version>
</dependency>


<dependency>
<groupId>org.apache.poi</groupId>
<artifactId>poi-ooxml</artifactId>
<version>3.17</version>
</dependency>


<dependency>
            <groupId>com.monitorjbl</groupId>
            <artifactId>xlsx-streamer</artifactId>
            <version>2.1.0</version>
            <scope>test</scope>
        </dependency>

**Comment by SujathaThazhal** [comment]
Along with the above dependencies I am using fasterxml, So the
simpleXmlReader instance is changed to

com.ctc.wstx.stax.WstxInputFactory

com.ctc.wstx.sr.ValidatingStreamReader, which not create any attribute for
Id. is there any way to fetch the sheet with out ID. even I use
sheet.getName is not working when i try to open the  sheet.openStream



<dependency>
<groupId>com.fasterxml.jackson.core</groupId>
<artifactId>jackson-databind</artifactId>
<version>${jackson.version}</version>
</dependency>

<dependency>
<groupId>com.fasterxml.jackson.core</groupId>
<artifactId>jackson-core</artifactId>
<version>${jackson.version}</version>
</dependency>

<dependency>
<groupId>com.fasterxml.jackson.core</groupId>
<artifactId>jackson-annotations</artifactId>
<version>${jackson.version}</version>
</dependency>

<dependency>
<groupId>com.fasterxml.jackson.dataformat</groupId>
<artifactId>jackson-dataformat-xml</artifactId>
<version>${jackson.version}</version>
</dependency>

**Comment by rzymek** [comment]
Upgrade to 0.10.1
It should fix your problem.

**Comment by SujathaThazhal** [comment]
Dear Dhatim/Fastexcel Team,

Thanks a lot,  Now it is working.  :)

**Comment by SujathaThazhal** [comment]
Dear Team,

This is only working with .xlsx files, not with .xls file.

**Comment by ochedru** [comment]
Fastexcel does not support the older `xls` format.
