### ISSUE TITLE
getCellAsBoolean always returns true

### ISSUE THREAD

**Issue by djuju08** [dhatim/fastexcel#77]
I think there is an issue with the getCellAsBoolean method of the Row.java class.

If a boolean value is set in the cell (TRUE or FALSE), the value retrieved by the library is always true.

**Comment by rzymek** [comment]
Confirmed. With [this xlsx](https://gist.github.com/rzymek/3fb79e4d997b08d8bff2139991ba2d13/raw/757caeb59e437e72989b6d05914c6b2441d10ba6/simple.xlsx) the following test fails:
```
@Test
public void asBoolean() throws Exception {
    try (InputStream is = openResource("/xlsx/simple.xlsx"); ReadableWorkbook wb = new ReadableWorkbook(is)) {
        List<Boolean> cells = wb.getFirstSheet().openStream()
                .flatMap(r -> r.stream())
                .filter(c -> !CellType.EMPTY.equals(c.getType()))
                .map(c -> c.asBoolean())
                .collect(toList());
        assertEquals(Arrays.asList(true,false), cells);
    }
}
```

**Comment by rzymek** [comment]
Self contained test using fastexcel writer and reader: https://github.com/rzymek/issue77
Also fails.
