### ISSUE TITLE
Cannot open output in Libreoffice

### ISSUE THREAD

**Issue by akbertram** [dhatim/fastexcel#82]
I'm unable to open output in LibreOffice Calc from a simple test case from fastexcel-writer 0.10.7:

```.java
public class FastExcelTest {

    @Test
    public void simpleWorkbook() throws IOException {
        OutputStream os = new FileOutputStream("/tmp/test2.xlsx");
        Workbook wb = new Workbook(os, "MyApplication", "1.0");
        Worksheet ws = wb.newWorksheet("Sheet 1");
        ws.value(0, 0, "This is a string in A1");
        ws.finish();
        wb.finish();
        os.close();
    }
}
```

If I try to open it in LibreOffice Calc, I get the message:

> The file 'test2.xlsx' is corrupt and therefore cannot be opened. LibreOffice can try to repair the file.

If I choose "Yes", LibreOffice is unsuccessfully with the repair.

Am I missing something?

The version of LibreOffice is:

> Version: 5.1.6.2
> Build ID: `1:5.1.6~rc2-0ubuntu1~xenial7`

**Comment by akbertram** [comment]
Nevermind, was not actually using fastexcel-writer 0.10.7! It works with the latest version.

**Comment by rzymek** [comment]
Yep, it was fixed by https://github.com/dhatim/fastexcel/commit/e31d1e5c1653f6644a30ff50898aaf6191fa163c  (downstream: https://github.com/rzymek/opczip/commit/d84563b576788f29245d50c1ab3b92fca9af99ea)
