### ISSUE TITLE
Create custom headers and footers

### ISSUE THREAD

**Issue by kjspahn** [dhatim/fastexcel#83]
Add the ability to write to headers and footers on the workbook/sheets

See: https://www.javatpoint.com/apache-poi-excel-header

**Comment by ochedru** [comment]
This is not supported. But why not use Apache POI to add headers and footers to your fastexcel-generated workbook?

**Comment by kjspahn** [comment]
Is there a way to read the workbook before exporting it?

**Comment by kjspahn** [comment]
Looking into that, is there a way to convert the fastexcel workbook to one that we can use for Apache POI before exporting it?

**Comment by ochedru** [comment]
> Looking into that, is there a way to convert the fastexcel workbook to one that we can use for Apache POI before exporting it?

No: you have to open with POI the workbook written by fastexcel.
