### ISSUE TITLE
Read percentage and currency

### ISSUE THREAD

**Issue by DAMH2017** [dhatim/fastexcel#84]
Facing problem while reading percentage (ex: 68% in excel file converted to 0.68), currency sign not supported also

**Comment by ochedru** [comment]
Can you post some example code? Thank you.

**Comment by DAMH2017** [comment]
I made the code as simple as possible for just trying, I have a file on desktop (Book1.xlsx) has a sheet called (Sheet1), cell (C1) has a value (68%) with percentage format
My code was:
`
ReadableWorkbook wb=null;
        try {
            wb = new ReadableWorkbook(new File("C:\\Users\\CompuFast\\Desktop\\Book1.xlsx"));
            Sheet sheet = wb.findSheet("Sheet1").get();
            System.out.println(sheet.read().get(0).getCell(2).getText());
//            System.out.println(new DataFormatter().formatCellValue((Cell)sheet.read().get(0).getCell(2)));
        } catch (IOException | InvalidOperationException ex) {
            System.out.println("Error in opening file: "+ex.getMessage());
        } finally {
            try{
                if(wb!=null) {
                    wb.close();
                    System.out.println("File closed");
                }
            
            } catch(IOException e) {
                System.out.println("Error in closing: "+e.getMessage());
            }
        }
`

Output was (0.68)

**Comment by rzymek** [comment]
fastexcel-reader ignores styles and formats for performance benefits. The information that 0.68 should be displayed as 68% is stored as style information in xlsx. You will not be able to get formatting/style information using fastexcel-reader. This is currently out of scope of this project. Try https://github.com/monitorjbl/excel-streaming-reader

**Comment by DAMH2017** [comment]
Well, it would be cool if this feature was there, anyway I will think for alternatives, also study excel streaming reader
I appreciate your efforts and thank you for the good work
