### ISSUE TITLE
Support for pane freeze

### ISSUE THREAD

**Issue by nagin** [dhatim/fastexcel#85]

**Comment by nagin** [comment]
Thanks for grate and lightweight library. It would nice if you could incorporate freeze pane functinality

**Comment by ochedru** [comment]
This is not supported. You can still use Apache POI to add a freeze pane to your fastexcel-generated workbook: https://poi.apache.org/components/spreadsheet/quick-guide.html#Splits.

**Comment by rnavarropiris** [comment]
I would also love to see this feature added to the library :)
