### ISSUE TITLE
Is there any possibility bring image in fast-excel?

### ISSUE THREAD

**Issue by shajahan86** [dhatim/fastexcel#90]
Hi,
We are using fast-excel more often in our project. It is working faster than other plugin. 
But we can't include logo in excel cell. 
Will you bring this feature in future or no idea about it?

Thanks

**Comment by ochedru** [comment]
To achieve this, you can still open the fast-excel generated workbook with Apache POI and add your logo to it.

**Comment by shajahan86** [comment]
Hi,
Thanks for your support.
Can you provide some better example to achieve this? If possible.

**Comment by rzymek** [comment]
Take a look at this example: https://stackoverflow.com/a/33721090/211205

**Comment by vSrkth** [comment]
Hi,
Is there any updates on this ticket.
If not, to achieve this do we need to add one more dependency into the project ..?
