### ISSUE TITLE
Read metadata properties

### ISSUE THREAD

**Issue by sebastian-raubach** [dhatim/fastexcel#93]
Are you thinking about adding functionality to read the metadata properties of an Excel file?

Like these here: https://support.office.com/en-us/article/view-or-change-the-properties-for-an-office-file-21d604c2-481e-4379-8e54-1dd4622c6b75

**Comment by ochedru** [comment]
This project focuses only on performance when reading or writing Excel files. Advanced operations like the one you describe are out of scope, and most of them can be achieved using Apache POI on the workbook generated by fastexcel. For example: https://stackoverflow.com/questions/43796819/how-to-write-metadata-into-excel-workbooks-using-apache-poi-in-java.
